INSERT INTO POZWZDNIPRAC (
	ID_POZWZDNIPRAC, 
	ID_WZORDNIPRAC, 
	ID_SYMBDNIAWZORCA, 
	"DATA")
SELECT
	Gen_id(GEN_POZWZDNIPRACY,1),
	MAX(w.ID_WZORDNIPRAC) AS ID_WZORDNIPRAC,
	MAX(p.KAL_NAZWISKOIMIE),
    CASE
        WHEN xrs.PRESTIGE_ZMIANA = 'I' THEN CAST(10001 AS INTEGER)
        WHEN xrs.PRESTIGE_ZMIANA = 'II' THEN CAST(10002 AS INTEGER)
        WHEN xrs.PRESTIGE_ZMIANA = 'III' THEN CAST(10003 AS INTEGER)
        WHEN xrs.PRESTIGE_ZMIANA = 'B' THEN CAST(10004 AS INTEGER)
        WHEN xrs.PRESTIGE_ZMIANA = '7' THEN CAST(10010 AS INTEGER)
        WHEN xrs.PRESTIGE_ZMIANA = '7,5' THEN CAST(10011 AS INTEGER)
    END AS ID_SYMBOLDNIWZORCA,
    CAST (xrs.RCP_DZIEN AS TIMESTAMP) AS "DATA"
FROM
    XXX_RCP_SCHEDULES xrs
INNER JOIN PRACOWNIK p ON
    p.NRUNIK = xrs.RCP_ID
INNER JOIN ANGAZ a ON a.ID_PRACOWNIK = p.ID_PRACOWNIK 
INNER JOIN ZASZEREG z ON z.ID_ANGAZ = a.ID_ANGAZ 
INNER JOIN WZORDNIPRAC w ON w.ID_WZORDNIPRAC = z.ID_WZORDNIPRAC 
GROUP BY
    ID_SYMBOLDNIWZORCA,
    "DATA";
   
