begin
     try
        begin
          ExecuteSQL('INSERT INTO NADGODZINY ( ID_NADGODZINY, ID_ANGAZ, ILOSCNADG50, ILOSCNADG100, ILOSCSZKODLIWE_I, ILOSCSZKODLIWE_II, ILOSCSZKODLIWE_III, ILOSCGODZINNOCNYCH, "DATA", ILOSCSZKODLIWE_IV, ILOSCSZKODLIWE_V, ILOSCSZKODLIWE_VI, ILOSCPOSTOJOWE ) SELECT Gen_id(GEN_NADGODZINY, 1), a.ID_ANGAZ, 0.0000 AS ILOSCNADG50, 0.0000 AS ILOSCNADG100, SUM(CASE WHEN xre.CHECK_TYPE = 0 THEN xre.CZAS_SUMA ELSE 0.0000 END) AS ILOSCSZKODLIWE_I, SUM(CASE WHEN xre.CHECK_TYPE = 1 THEN xre.CZAS_SUMA ELSE 0.0000 END) AS ILOSCSZKODLIWE_II, 0.0000 AS ILOSCSZKODLIWE_III, 0.0000 AS ILOSCGODZINNOCNYCH, MAX(CAST(xre."DATA" AS TIMESTAMP)) AS "DATA", 0.0000 AS ILOSCSZKODLIWE_IV, 0.0000 AS ILOSCSZKODLIWE_V, 0.0000 AS ILOSCSZKODLIWE_VI, 0.0000 AS ILOSCPOSTOJOWE FROM PRACOWNIK p JOIN XXX_RCP_EVENTS xre ON xre.EXT_BADGE = p.NRUNIK JOIN ANGAZ a ON a.ID_PRACOWNIK = p.ID_PRACOWNIK WHERE p.NRUNIK = xre.EXT_BADGE GROUP BY a.ID_ANGAZ, CAST(xre."DATA" AS TIMESTAMP)', 0);
          ShowMessage('Operacja zakończona pomyślnie.');
        end;
     except
        begin
            ShowMessage('Wystąpił błąd. '); // Wyświetlenie komunikatu w przypadku błędu
        end;
    end;
end.
