CREATE TRIGGER XXX_ETAPAKCEPT_ZPO FOR ETAPAKCEPT BEFORE INSERT
AS
DECLARE VARIABLE ID_MAX INTEGER;
BEGIN
	SELECT MAX(s.ID_SCIEZKAAKCEPT) FROM SCIEZKAAKCEPT s WHERE s.Nazwa = 'Zapotrzebowanie / Inwestycje' INTO :ID_MAX;
UPDATE
	ETAPAKCEPT
SET
	AKTUALNY = CASE
		WHEN LP = 2
		AND ID_SCIEZKAAKCEPT = :ID_MAX  THEN 0
		WHEN LP = 3
		AND ID_SCIEZKAAKCEPT = :ID_MAX THEN 1
		ELSE AKTUALNY
	END,
	AKTUALNY_COUNT = CASE
		WHEN LP = 3
		AND ID_SCIEZKAAKCEPT = :ID_MAX THEN 1
		ELSE AKTUALNY_COUNT
	END
WHERE
	(ID_SCIEZKAAKCEPT = :ID_MAX);
END
